backend/app.js, backend/config/supabaseClient.js, backend/models/appointment.js, backend/package-lock.json, backend/package.json, backend/routes/appointmentRoutes.js, backend/routes/doctorRoutes.js, backend/routes/userRoutes.js, package-lock.json
@aryamagarwal 
THE BACKEND SERVER IS UP AND RUNNING!
Added `.env` file separately for backend in backend folder
Made a supabase account  and project and entered the supabase key an url using it .
`.env` format --->
`
MONGO_URI=
SUPABASE_URL=
SUPABASE_KEY=
PORT=5000
`
=> Backend Server Up and Running

backend/config/verifyToken.js, backend/routes/userRoutes.js, frontend/src/components/PatientDashboard/EditProfile.jsx, frontend/src/components/PatientDashboard/ProfileTab.jsx, frontend/src/hooks/useCheckLogin.js, frontend/src/hooks/useGetCurrentUser.js, frontend/src/hooks/useGetUserDetails.js, frontend/src/hooks/useHandleEditProfile.js, frontend/src/hooks/useHandleSignUp.js, frontend/src/hooks/useUpdateUserProfilePicture.js, frontend/src/hooks/useUserRoleById.js, frontend/src/pages/AccountVerification.jsx, frontend/src/pages/Dashboard.jsx, frontend/src/pages/LoginPage.jsx, frontend/src/pages/SignUpPage.jsx, frontend/src/utils/api.js
@aryamagarwal 
@hitarth-gg 
Implemented `POST`, `PUT`, and `GET` requests using TanStack Query in a structured and efficient format.
Reusable Hooks
1)`useCheckLogin() `--> To check Login credentials of current User
2)`useGetCurrentUser() `---> To get the current user credentials such as {`email`,`email_confirmed_at`}
3)`useUserRoleById(userId, token)`--->To get the users `role` by id (from profiles table) 
4)`useUpdateUserProfilePicture() `--> To upload the User Profile Picture 
5)`useHandleEditProfile()`-->To update user details
6)`useGetUserDetails(userId, accessToken)`--> To get Current User Details
Also New Feature(missing in previous upgrades)
1)Now user when verifies the email in `\verification` page then he is navigated to `\verified` page
2)Also used mutations in the …
=> Fetch Requests for user made in required format

backend/routes/doctorRoutes.js, backend/routes/profileRoutes.js, backend/routes/userRoutes.js, frontend/src/components/Header.jsx, frontend/src/components/PatientDashboard/EditProfile.jsx, frontend/src/components/PatientDashboard/ProfileTab.jsx, frontend/src/hooks/useHandleEditProfile.js, frontend/src/hooks/useHandleSignUp.js, frontend/src/hooks/useUpdateUserProfilePicture.js, frontend/src/pages/AccountVerification.jsx, frontend/src/utils/api.js
@aryamagarwal 
Final changes made in login, logout , signup, signin, profile update and fetching
=> Changes made 

backend/routes/userRoutes.js, frontend/src/App.jsx, frontend/src/hooks/useResetPassword.js, frontend/src/pages/ForgotPassword.jsx, frontend/src/pages/LoginPage.jsx, frontend/src/pages/ResetPassword.jsx, frontend/src/pages/ResetPasswordEmailSent.jsx, frontend/src/utils/api.js
@aryamagarwal 
Added the Forgot password Cycle
a)User clicks on forgot password
b)User is navigated to a page where he has to enter his email(registered email) `user/resetPassEnterEmail`
c)User Clicks on Reset button and a email comes at his registered email
d)The email contains a link to a page where he has to enter his password the password should be in accordance with `passwordRegex` and he is showed error messages accordingly
e)The button is disabled untill the password is not in accordance with `passwordRegex` and if `confirm password!==password`
f)Upon clicking `reset` password button 
if there is no error then user is navigated to login
if there is error then user is shown the error using `errorMessage`
g)User can now login using his new password
=> Forgot Password?reset Password Cycle added

frontend/src/App.jsx, frontend/src/components/PatientDashboard/EditProfile.jsx, frontend/src/pages/AccountVerification.jsx, frontend/src/pages/Dashboard.jsx, frontend/src/pages/ForgotPassword.jsx, frontend/src/pages/LoginPage.jsx, frontend/src/pages/ResetPassword.jsx, frontend/src/pages/ResetPasswordEmailSent.jsx, frontend/src/pages/SignUpPage.jsx, package-lock.json, package.json
@aryamagarwal 
Toast Messages have been added 
1)On LogIn
2)On SignIn
3)On reset Password
and Edit profile changes made
=> Toast Messages added

frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/components/Container1.jsx, frontend/src/components/DoctorDashboard/DoctorDashboard.jsx, frontend/src/components/DoctorDashboard/DoctorQueueCard.jsx, frontend/src/components/DoctorDashboard/SkipAppointment.jsx, frontend/src/components/FeatureCard.jsx, frontend/src/components/Header.jsx, frontend/src/components/PatientDashboard/Feedback.jsx, frontend/src/components/PatientDashboard/HistoryAppointmentCard.jsx, frontend/src/components/PatientDashboard/PatientDashboard.jsx, frontend/src/pages/AccountVerification.jsx, frontend/src/pages/AccountVerified.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/LoginPage.jsx, frontend/src/ui/AppLayout.jsx
- Fix: Remove OTP Modal after OTP Verification
- Fix: sub-routing on dashboard
- Added Feedback modal.
- Changed Home page UI.
=> UI Overhaul + Feedback modal

backend/package-lock.json, backend/package.json, frontend/src/components/BookingFormSelectSlots.jsx, frontend/src/components/DoctorDashboard/DoctorQueueCard.jsx, frontend/src/components/DoctorDashboard/SeeDetails.jsx, frontend/src/components/Header.jsx, frontend/src/pages/Dashboard.jsx, frontend/src/pages/Home.jsx
- Dashboard mobile view fixed
- Disabling skip button post OTP verification
- BookAppointment default calendar date set to today
- Closing see details dialog after appointment successfully saved and marked done
- Added home button in navbar
=> Minor fixes

.github/workflows/deploy.yml, backend/package.json, frontend/index.html, frontend/package-lock.json, frontend/package.json, frontend/public/404.html, frontend/src/App.jsx, frontend/src/components/BookingFormSelectSlots.jsx, frontend/src/components/DoctorSlotCard.jsx, frontend/src/pages/BookAppointment.jsx, frontend/vite.config.js
- Max of 4  tags will be shown.
=> Feedback Tags added to Doctor Slot Card.

README.md
@aryamagarwal 
Implementation Flowchart added for documentation
=> docs: Implementation Flowchart

README.md
Now the flowchart would be displayed according to the background of github earlier version of flowchart was only for dark theme of github 
also the flowchart has been modified
=> docs: Flowchart modified

README.md, backend/routes/feedbackRoutes.js, frontend/src/pages/LoginPage.jsx, frontend/src/pages/SignUpPage.jsx, frontend/src/utils/api.js
@aryamagarwal 
@Invincible1602 
Modified the ML Models API endpoint since the former API got expired.
Kindly look into the changes.
=> refactor: Update ML model endpoint

frontend/package-lock.json, frontend/package.json, frontend/src/pages/Home.jsx, frontend/src/pages/MultiDoctorDashboard.jsx
Core logic of backend fetching and all remains same
=> refactor:UI improvements for queue monitoring system

README.md, frontend/src/pages/Home.jsx
=> docs: Update README.md

backend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/src/components/DoctorDashboard/DoctorHistoryCard.jsx, frontend/src/components/DoctorDashboard/DoctorProfileTab.jsx, frontend/src/components/DoctorDashboard/DoctorQueue.jsx, frontend/src/components/DoctorDashboard/DoctorQueueCard.jsx
=> ✅: Doctor Queue UI Enhanced

backend/app.js, backend/routes/healthWorkerRoutes.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/components/HealthWorkerDashboard/HealthCampRegistration.jsx, frontend/src/components/HealthWorkerDashboard/HealthWorkerDashboard.jsx, frontend/src/components/HealthWorkerDashboard/HealthWorkerProfileTab.jsx, frontend/src/components/HealthWorkerDashboard/PatientHealthCheckupform.jsx, frontend/src/pages/Dashboard.jsx, frontend/src/pages/HealthCampList.jsx, frontend/src/pages/HealthCamps.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/MultiDoctorDashboard.jsx
Health Worker Profile
Patient Health Assessment
Health Camp Registration
Home page 
Health Camps List for reception+healthworker+patients
Health Camps List for doctors
Health Camp List expand
Volunteer confirmation for doctors
Working and avoids overlapping Health camps for same doctor
in frontend
add env  variable
`VITE_API_GOOGLE_MAPS_API_KEY`
healthWorker credentials
healthworker1@example.com
HEALTH123
=> feat: Health worker(NGO etc) dashboard

frontend/src/components/PatientDashboard/AppointmentCard.jsx, frontend/src/components/PatientDashboard/CancelDialog.jsx, frontend/src/components/PatientDashboard/HistoryAppointmentCard.jsx
=> ✅: Patient Queue & History Card UI Enhanced

frontend/src/pages/Home.jsx
=> fix:Route Protected `Health Camps`

backend/routes/appointmentRoutes.js, backend/routes/doctorProfileRoutes.js, backend/routes/multiDoctorDashboardRoutes.js, frontend/src/pages/MultiDoctorDashboard.jsx
=> fix: update backend to use new appointments and doctors reference table 

backend/routes/userRoutes.js, frontend/src/components/PatientDashboard/QRscanner.jsx
=> fix:Reception QR fixed

backend/app.js, backend/routes/AiConsultation.js, frontend/src/App.jsx, frontend/src/pages/AIConsultation.jsx
This feature would also help in greatly reducing overcrowding
[Screencast from 26-04-25 08:30:50 PM IST.webm](https://github.com/user-attachments/assets/8ec01262-0366-4dfd-bf63-e7b0cec6d1cf)
=> feat: AIConsultation added

backend/package-lock.json, backend/package.json, backend/routes/AiConsultation.js, frontend/src/pages/AIConsultation.jsx
Using Google TTS for AIConsultation instead of ElevenLabs(Due to certain restrictions and errors)
=> Google TTS instead of ElevenLabs

frontend/src/pages/AIConsultation.jsx
=> refactor:UI changes AIConsultation 

backend/routes/AiConsultation.js
The voice now supports hindi and hinglish translations too.
=> #fix:en-US voice changed to en-IN
